// flow-typed signature: 20b98471c7c1657ed53a4ee7954f137f
// flow-typed version: <<STUB>>/postcss-for_v^2.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-for'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-for' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-for/index' {
  declare module.exports: $Exports<'postcss-for'>;
}
declare module 'postcss-for/index.js' {
  declare module.exports: $Exports<'postcss-for'>;
}
