// flow-typed signature: 84a3ab13999acf42437ffa8a9e409421
// flow-typed version: <<STUB>>/snapsvg_v^0.5.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snapsvg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'snapsvg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snapsvg/demos/animated-game/js/backbone' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/animated-game/js/jquery-1.9.0.min' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/animated-game/js/main' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/animated-game/js/path-animal' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/animated-game/js/seedrandom' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/animated-game/js/snap.svg' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/animated-game/js/tree-face' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/animated-game/js/underscore' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/Gruntfile' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/site/js/main' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/site/js/vendor/modernizr.min' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/site/js/vendor/require' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/site/js/vendor/require.min' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/app/app' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/app/burst' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/app/device' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/app/heart' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/app/logo' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/app/mesh' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/main' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Color' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Core' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Geometry' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Light' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Material' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Math' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Mesh' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Object' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Plane' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Renderer' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Scene' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/SVGRenderer' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Triangle' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Vector3' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Vector4' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Vertex' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/modernizr.min' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/require' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/require.min' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/snap.svg-min' {
  declare module.exports: any;
}

declare module 'snapsvg/demos/snap-ad/src/js/vendor/snap.svg' {
  declare module.exports: any;
}

declare module 'snapsvg/dist/snap.svg-min' {
  declare module.exports: any;
}

declare module 'snapsvg/dist/snap.svg' {
  declare module.exports: any;
}

declare module 'snapsvg/doc/js/prism' {
  declare module.exports: any;
}

declare module 'snapsvg/Gruntfile' {
  declare module.exports: any;
}

declare module 'snapsvg/src/align' {
  declare module.exports: any;
}

declare module 'snapsvg/src/amd-banner' {
  declare module.exports: any;
}

declare module 'snapsvg/src/amd-footer' {
  declare module.exports: any;
}

declare module 'snapsvg/src/animation' {
  declare module.exports: any;
}

declare module 'snapsvg/src/attr' {
  declare module.exports: any;
}

declare module 'snapsvg/src/attradd' {
  declare module.exports: any;
}

declare module 'snapsvg/src/class' {
  declare module.exports: any;
}

declare module 'snapsvg/src/colors' {
  declare module.exports: any;
}

declare module 'snapsvg/src/copy' {
  declare module.exports: any;
}

declare module 'snapsvg/src/element' {
  declare module.exports: any;
}

declare module 'snapsvg/src/equal' {
  declare module.exports: any;
}

declare module 'snapsvg/src/filter' {
  declare module.exports: any;
}

declare module 'snapsvg/src/matrix' {
  declare module.exports: any;
}

declare module 'snapsvg/src/mina' {
  declare module.exports: any;
}

declare module 'snapsvg/src/mouse' {
  declare module.exports: any;
}

declare module 'snapsvg/src/paper' {
  declare module.exports: any;
}

declare module 'snapsvg/src/path' {
  declare module.exports: any;
}

declare module 'snapsvg/src/set' {
  declare module.exports: any;
}

declare module 'snapsvg/src/svg' {
  declare module.exports: any;
}

declare module 'snapsvg/test/attradd' {
  declare module.exports: any;
}

declare module 'snapsvg/test/attrs' {
  declare module.exports: any;
}

declare module 'snapsvg/test/class' {
  declare module.exports: any;
}

declare module 'snapsvg/test/colors' {
  declare module.exports: any;
}

declare module 'snapsvg/test/element' {
  declare module.exports: any;
}

declare module 'snapsvg/test/filter' {
  declare module.exports: any;
}

declare module 'snapsvg/test/gradients' {
  declare module.exports: any;
}

declare module 'snapsvg/test/matrix' {
  declare module.exports: any;
}

declare module 'snapsvg/test/mina' {
  declare module.exports: any;
}

declare module 'snapsvg/test/paper' {
  declare module.exports: any;
}

declare module 'snapsvg/test/path' {
  declare module.exports: any;
}

declare module 'snapsvg/test/primitives' {
  declare module.exports: any;
}

declare module 'snapsvg/test/set' {
  declare module.exports: any;
}

declare module 'snapsvg/test/snap-tests' {
  declare module.exports: any;
}

declare module 'snapsvg/test/system' {
  declare module.exports: any;
}

declare module 'snapsvg/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snapsvg/demos/animated-game/js/backbone.js' {
  declare module.exports: $Exports<'snapsvg/demos/animated-game/js/backbone'>;
}
declare module 'snapsvg/demos/animated-game/js/jquery-1.9.0.min.js' {
  declare module.exports: $Exports<'snapsvg/demos/animated-game/js/jquery-1.9.0.min'>;
}
declare module 'snapsvg/demos/animated-game/js/main.js' {
  declare module.exports: $Exports<'snapsvg/demos/animated-game/js/main'>;
}
declare module 'snapsvg/demos/animated-game/js/path-animal.js' {
  declare module.exports: $Exports<'snapsvg/demos/animated-game/js/path-animal'>;
}
declare module 'snapsvg/demos/animated-game/js/seedrandom.js' {
  declare module.exports: $Exports<'snapsvg/demos/animated-game/js/seedrandom'>;
}
declare module 'snapsvg/demos/animated-game/js/snap.svg.js' {
  declare module.exports: $Exports<'snapsvg/demos/animated-game/js/snap.svg'>;
}
declare module 'snapsvg/demos/animated-game/js/tree-face.js' {
  declare module.exports: $Exports<'snapsvg/demos/animated-game/js/tree-face'>;
}
declare module 'snapsvg/demos/animated-game/js/underscore.js' {
  declare module.exports: $Exports<'snapsvg/demos/animated-game/js/underscore'>;
}
declare module 'snapsvg/demos/snap-ad/Gruntfile.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/Gruntfile'>;
}
declare module 'snapsvg/demos/snap-ad/site/js/main.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/site/js/main'>;
}
declare module 'snapsvg/demos/snap-ad/site/js/vendor/modernizr.min.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/site/js/vendor/modernizr.min'>;
}
declare module 'snapsvg/demos/snap-ad/site/js/vendor/require.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/site/js/vendor/require'>;
}
declare module 'snapsvg/demos/snap-ad/site/js/vendor/require.min.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/site/js/vendor/require.min'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/app/app.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/app/app'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/app/burst.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/app/burst'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/app/device.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/app/device'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/app/heart.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/app/heart'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/app/logo.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/app/logo'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/app/mesh.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/app/mesh'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/main.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/main'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Color.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Color'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Core.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Core'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Geometry.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Geometry'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Light.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Light'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Material.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Material'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Math.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Math'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Mesh.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Mesh'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Object.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Object'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Plane.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Plane'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Renderer.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Renderer'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Scene.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Scene'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/SVGRenderer.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/SVGRenderer'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Triangle.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Triangle'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Vector3.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Vector3'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Vector4.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Vector4'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/fss/Vertex.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/fss/Vertex'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/modernizr.min.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/modernizr.min'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/require.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/require'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/require.min.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/require.min'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/snap.svg-min.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/snap.svg-min'>;
}
declare module 'snapsvg/demos/snap-ad/src/js/vendor/snap.svg.js' {
  declare module.exports: $Exports<'snapsvg/demos/snap-ad/src/js/vendor/snap.svg'>;
}
declare module 'snapsvg/dist/snap.svg-min.js' {
  declare module.exports: $Exports<'snapsvg/dist/snap.svg-min'>;
}
declare module 'snapsvg/dist/snap.svg.js' {
  declare module.exports: $Exports<'snapsvg/dist/snap.svg'>;
}
declare module 'snapsvg/doc/js/prism.js' {
  declare module.exports: $Exports<'snapsvg/doc/js/prism'>;
}
declare module 'snapsvg/Gruntfile.js' {
  declare module.exports: $Exports<'snapsvg/Gruntfile'>;
}
declare module 'snapsvg/src/align.js' {
  declare module.exports: $Exports<'snapsvg/src/align'>;
}
declare module 'snapsvg/src/amd-banner.js' {
  declare module.exports: $Exports<'snapsvg/src/amd-banner'>;
}
declare module 'snapsvg/src/amd-footer.js' {
  declare module.exports: $Exports<'snapsvg/src/amd-footer'>;
}
declare module 'snapsvg/src/animation.js' {
  declare module.exports: $Exports<'snapsvg/src/animation'>;
}
declare module 'snapsvg/src/attr.js' {
  declare module.exports: $Exports<'snapsvg/src/attr'>;
}
declare module 'snapsvg/src/attradd.js' {
  declare module.exports: $Exports<'snapsvg/src/attradd'>;
}
declare module 'snapsvg/src/class.js' {
  declare module.exports: $Exports<'snapsvg/src/class'>;
}
declare module 'snapsvg/src/colors.js' {
  declare module.exports: $Exports<'snapsvg/src/colors'>;
}
declare module 'snapsvg/src/copy.js' {
  declare module.exports: $Exports<'snapsvg/src/copy'>;
}
declare module 'snapsvg/src/element.js' {
  declare module.exports: $Exports<'snapsvg/src/element'>;
}
declare module 'snapsvg/src/equal.js' {
  declare module.exports: $Exports<'snapsvg/src/equal'>;
}
declare module 'snapsvg/src/filter.js' {
  declare module.exports: $Exports<'snapsvg/src/filter'>;
}
declare module 'snapsvg/src/matrix.js' {
  declare module.exports: $Exports<'snapsvg/src/matrix'>;
}
declare module 'snapsvg/src/mina.js' {
  declare module.exports: $Exports<'snapsvg/src/mina'>;
}
declare module 'snapsvg/src/mouse.js' {
  declare module.exports: $Exports<'snapsvg/src/mouse'>;
}
declare module 'snapsvg/src/paper.js' {
  declare module.exports: $Exports<'snapsvg/src/paper'>;
}
declare module 'snapsvg/src/path.js' {
  declare module.exports: $Exports<'snapsvg/src/path'>;
}
declare module 'snapsvg/src/set.js' {
  declare module.exports: $Exports<'snapsvg/src/set'>;
}
declare module 'snapsvg/src/svg.js' {
  declare module.exports: $Exports<'snapsvg/src/svg'>;
}
declare module 'snapsvg/test/attradd.js' {
  declare module.exports: $Exports<'snapsvg/test/attradd'>;
}
declare module 'snapsvg/test/attrs.js' {
  declare module.exports: $Exports<'snapsvg/test/attrs'>;
}
declare module 'snapsvg/test/class.js' {
  declare module.exports: $Exports<'snapsvg/test/class'>;
}
declare module 'snapsvg/test/colors.js' {
  declare module.exports: $Exports<'snapsvg/test/colors'>;
}
declare module 'snapsvg/test/element.js' {
  declare module.exports: $Exports<'snapsvg/test/element'>;
}
declare module 'snapsvg/test/filter.js' {
  declare module.exports: $Exports<'snapsvg/test/filter'>;
}
declare module 'snapsvg/test/gradients.js' {
  declare module.exports: $Exports<'snapsvg/test/gradients'>;
}
declare module 'snapsvg/test/matrix.js' {
  declare module.exports: $Exports<'snapsvg/test/matrix'>;
}
declare module 'snapsvg/test/mina.js' {
  declare module.exports: $Exports<'snapsvg/test/mina'>;
}
declare module 'snapsvg/test/paper.js' {
  declare module.exports: $Exports<'snapsvg/test/paper'>;
}
declare module 'snapsvg/test/path.js' {
  declare module.exports: $Exports<'snapsvg/test/path'>;
}
declare module 'snapsvg/test/primitives.js' {
  declare module.exports: $Exports<'snapsvg/test/primitives'>;
}
declare module 'snapsvg/test/set.js' {
  declare module.exports: $Exports<'snapsvg/test/set'>;
}
declare module 'snapsvg/test/snap-tests.js' {
  declare module.exports: $Exports<'snapsvg/test/snap-tests'>;
}
declare module 'snapsvg/test/system.js' {
  declare module.exports: $Exports<'snapsvg/test/system'>;
}
declare module 'snapsvg/test/test.js' {
  declare module.exports: $Exports<'snapsvg/test/test'>;
}
